### ISSUE TITLE
falta el makefile

### ISSUE THREAD

**Issue by maltalef101** [GuidoDipietro/tpAutomatas#1]
[EDITED by owner]

Estimado:
¿Usted no me aprecia porque estoy a favor del código abierto y utilizo 'make'?
Por favor sea tan amable de incluir los comandos de gcc, lo apreciaré mucho.

Saludos cordiales.

**Comment by GuidoDipietro** [comment]
Estimado maltalef101,
usted puede crear un ejecutable del archivo .c que más le guste mediante:
```gcc -o archivoDestino archivoOrigen```
Véase README.md para conocer qué hace cada uno. Son individuales.

De todas formas, el objetivo de este Trabajo Práctico pasa por cómo están escritos los programas, y el foco no pasa por que un usuario los ejecute. De hecho ni siquiera debería haber usuarios de estos programas.

Un saludo cordial

**Comment by maltalef101** [comment]
puto
